on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - { goos: android, goarch: arm,    out: client-android-arm }
          - { goos: android, goarch: arm64,  out: client-android-arm64 }
          - { goos: linux,   goarch: arm,    out: tarm }
          - { goos: linux,   goarch: arm64,  out: tarm64 }
          - { goos: windows, goarch: amd64,  out: win.exe }

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Build Slipstream Client
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}
        run: |
          mkdir -p builds
          go build -trimpath -ldflags "-s -w" \
            -o builds/${{ matrix.target.out }} ./cmd/client

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: slipstream-client
          path: builds/
